Adding the MP role to the page
nebulab/playbook pull request #392
Opened 2022-08-29 15:36 UTC by nahemaandrade

The page only mentioned the directors which are the Managing Partners, so I added both roles now.

2022-09-09 16:11 UTC, mtylty approved these changes

2022-09-09 16:15 UTC, mtylty requested changes

2022-09-09 16:15 UTC, mtylty commented on source/company-rituals/all-hands-sessions.html.md
> +Managing Partners and Directors. We try to cover a variety of cross-cutting topics such as recent successes and failures
Similar problem as #393

2022-09-16 23:07 UTC, nahemaandrade commented on source/company-rituals/all-hands-sessions.html.md
> +Managing Partners and Directors. We try to cover a variety of cross-cutting topics such as recent successes and failures
The update was made 👍

2022-09-19 12:08 UTC, mtylty approved these changes

2022-09-19 13:15 UTC, merged